# Generated by Django 5.2.8 on 2025-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=2555)),
                ('affiliate_token', models.CharField(max_length=255)),
            ],
        ),
    ]
