# Generated by Django 5.2.8 on 2025-11-23 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit to Deriv'), ('withdrawal', 'Withdrawal from Deriv')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deriv_account_number', models.CharField(help_text='Your Deriv account number / CR number', max_length=50, verbose_name='Deriv Account/CR Number')),
                ('ecocash_number', models.CharField(help_text='Your EcoCash phone number', max_length=50)),
                ('ecocash_name', models.CharField(help_text='Name registered with your EcoCash', max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction fee', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('awaiting_pop', 'Awaiting POP')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(editable=False, max_length=9, unique=True)),
                ('ecocash_reference', models.CharField(blank=True, help_text='EcoCash reference number from POP', max_length=100, null=True, verbose_name='EcoCash Reference')),
                ('deriv_transaction_id', models.CharField(blank=True, help_text="Deriv's transaction reference after deposit", max_length=100, null=True)),
                ('ecocash_transaction_id', models.CharField(blank=True, help_text='EcoCash transaction ID for withdrawals', max_length=100, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Transaction description')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocash_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EcoCash Transaction',
                'verbose_name_plural': 'EcoCash Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Minimum amount for this fee range (inclusive)', max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Maximum amount for this fee range (inclusive)', max_digits=10)),
                ('fixed_charge', models.DecimalField(decimal_places=2, help_text='Fixed charge amount in USD', max_digits=10)),
                ('is_percentage', models.BooleanField(default=False, help_text='Whether this uses percentage calculation ($10+ range)')),
                ('percentage_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage rate (only for $10+ range)', max_digits=5)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Additional fixed fee (only for $10+ range)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction Charge',
                'verbose_name_plural': 'Transaction Charges',
                'ordering': ['min_amount'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_amount__lte', models.F('max_amount'))), name='min_amount_lte_max_amount')],
            },
        ),
        migrations.CreateModel(
            name='TransactionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_image', models.ImageField(blank=True, help_text='Screenshot of EcoCash POP', null=True, upload_to='receipts/%Y/%m/%d/')),
                ('receipt_number', models.CharField(blank=True, help_text='EcoCash receipt number', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Admin verification notes')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='finance.ecocashtransaction')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Receipt',
                'verbose_name_plural': 'Transaction Receipts',
            },
        ),
        migrations.AddIndex(
            model_name='ecocashtransaction',
            index=models.Index(fields=['status', 'created_at'], name='finance_eco_status_601568_idx'),
        ),
        migrations.AddIndex(
            model_name='ecocashtransaction',
            index=models.Index(fields=['user', 'created_at'], name='finance_eco_user_id_a62458_idx'),
        ),
        migrations.AddIndex(
            model_name='ecocashtransaction',
            index=models.Index(fields=['reference_number'], name='finance_eco_referen_914bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='ecocashtransaction',
            index=models.Index(fields=['ecocash_reference'], name='finance_eco_ecocash_f0010e_idx'),
        ),
    ]
