# Generated by Django 5.2.8 on 2025-12-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auditlog_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocashtransaction',
            name='reference_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
