# Generated by Django 5.2.8 on 2025-12-10 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_ecocashtransaction_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('price_per_transaction', models.DecimalField(decimal_places=3, default=0.005, max_digits=8)),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
