# Generated by Django 5.2.8 on 2025-12-21 12:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_billingcycle_price_per_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingcycle',
            name='deposit_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0075'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='billingcycle',
            name='withdrawal_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=8),
        ),
    ]
