# Generated by Django 5.2.8 on 2026-01-27 17:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_billingcycle_deposit_fee_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcycle',
            name='weltrade_fee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='ecocashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit to Deriv'), ('withdrawal', 'Withdrawal from Deriv'), ('weltrade_deposit', 'Deposit to Weltrade')], max_length=20),
        ),
    ]
