# Generated by Django 5.2.8 on 2026-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_billingcycle_weltrade_fee_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocashtransaction',
            name='deriv_account_number',
            field=models.CharField(help_text='Your Deriv account number / CR number', max_length=100, verbose_name='Deriv Account/CR Number'),
        ),
    ]
