# Generated by Django 5.2.8 on 2026-01-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_ecocashtransaction_deriv_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncharge',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit to Deriv'), ('withdrawal', 'Withdrawal from Deriv'), ('weltrade_deposit', 'Deposit to Weltrade')], default='weltrade_deposit', max_length=100),
        ),
    ]
