# Generated by Django 5.2.8 on 2026-01-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_transactioncharge_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncharge',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit to Deriv'), ('withdrawal', 'Withdrawal from Deriv'), ('weltrade_deposit', 'Deposit to Weltrade')], default='deposit', max_length=100),
        ),
    ]
