# Generated by Django 5.2.8 on 2026-02-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_transactioncharge_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocashtransaction',
            name='deriv_account_number',
            field=models.CharField(blank=True, help_text='Your Deriv account number / CR number', max_length=100, null=True, verbose_name='Deriv Account/CR Number'),
        ),
        migrations.AlterField(
            model_name='ecocashtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit to Deriv'), ('withdrawal', 'Withdrawal from Deriv'), ('weltrade_deposit', 'Deposit to Weltrade'), ('book_subscription', 'Book Subscription')], max_length=20),
        ),
    ]
