# Generated by Django 5.2.8 on 2025-12-13 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('transaction_success', 'Transaction Success'), ('transaction_failed', 'Transaction Failed'), ('marketing', 'Marketing Campaign'), ('promotional', 'Promotional Offer'), ('educational', 'Educational Content'), ('system', 'System Notification'), ('welcome', 'Welcome Message')], default='marketing', max_length=50)),
                ('audience_type', models.CharField(choices=[('all_users', 'All Users'), ('active_users', 'Active Users (30 days)'), ('new_users', 'New Users (7 days)'), ('verified_users', 'Verified Users'), ('unverified_users', 'Unverified Users'), ('depositors', 'Users with Deposits'), ('withdrawers', 'Users with Withdrawals'), ('specific', 'Specific Users')], default='all_users', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='marketing/attachments/')),
                ('send_immediately', models.BooleanField(default=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_clicks', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('open_rate', models.FloatField(default=0.0)),
                ('click_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
