# Generated by Django 5.2.8 on 2025-12-02 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=100)),
                ('txn_id', models.CharField(max_length=500, unique=True)),
                ('body', models.TextField()),
                ('new_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CashOutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('txn_id', models.CharField(max_length=500, unique=True)),
                ('body', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('verification_code', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('prev_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('new_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('flagged', models.BooleanField(default=False)),
                ('fradulent', models.BooleanField(default=False)),
                ('low_limit', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('flagged_by', models.CharField(blank=True, max_length=100, null=True)),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashout_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
