# Generated by Django 5.2.8 on 2025-12-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappsession_previous_step_initiateorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcocashPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecocash_pop', models.ImageField(upload_to='ecocash_pops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecocash_pops', to='whatsapp.initiateorders')),
            ],
        ),
    ]
