# Generated by Django 5.2.8 on 2025-12-06 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_switch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switch',
            old_name='description',
            new_name='off_message',
        ),
    ]
