# Generated by Django 5.2.8 on 2025-12-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_rename_description_switch_off_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocashpop',
            name='ecocash_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecocashpop',
            name='ecocash_pop',
            field=models.ImageField(blank=True, null=True, upload_to='ecocash_pops/'),
        ),
    ]
