# Generated by Django 5.2.8 on 2025-12-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0007_ecocashpop_ecocash_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocashpop',
            name='has_image',
            field=models.BooleanField(default=True),
        ),
    ]
