# Generated by Django 5.2.8 on 2025-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_ecocashpop_has_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='on_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
