# Generated by Django 5.2.8 on 2026-01-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_switch_on_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiateorders',
            name='order_type',
            field=models.CharField(choices=[('deriv_deposit', 'Deriv Deposit'), ('weltrade_deposit', 'Weltrade Deposit')], default='deriv_deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='initiateorders',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
    ]
