# Generated by Django 5.2.8 on 2026-02-01 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_switch_on_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiateorders',
            name='order_type',
            field=models.CharField(choices=[('deposit', 'Deriv Deposit'), ('weltrade_deposit', 'Weltrade Deposit')], default='deposit', max_length=50),
        ),
        migrations.AlterField(
            model_name='initiateorders',
            name='account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='switch',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('signals', 'Signals'), ('books', 'Books'), ('training', 'Training'), ('weltrade_deposit', 'Weltrade Deposit'), ('other', 'Other')], max_length=50),
        ),
    ]
