# Generated by Django 5.2.8 on 2026-01-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_initiateorders_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('signals', 'Signals'), ('books', 'Books'), ('training', 'Training'), ('weltrade_deposit', 'Weltrade Deposit'), ('other', 'Other')], max_length=50),
        ),
    ]
