# Generated by Django 5.2.8 on 2026-01-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_alter_switch_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientverification',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientverification',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
