# Generated by Django 5.2.8 on 2026-01-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_clientverification_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiateorders',
            name='order_type',
            field=models.CharField(choices=[('deposit', 'Deriv Deposit'), ('weltrade_deposit', 'Weltrade Deposit')], default='deposit', max_length=50),
        ),
    ]
