# Generated by Django 5.2.8 on 2026-02-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0014_alter_initiateorders_order_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiateSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecocash_number', models.CharField(max_length=15)),
                ('ecocash_message', models.TextField()),
                ('subscription_id', models.CharField(max_length=15)),
                ('subscription_type', models.CharField(choices=[('books', 'Books'), ('signals', 'Signals')], default='books', max_length=50)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
