# Generated by Django 5.2.8 on 2025-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='ecocash_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='pop_image',
            field=models.ImageField(blank=True, null=True, upload_to='pop/'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('2_week_plan', '2 Week Plan - $50'), ('monthly_plan', 'Monthly Plan - $80'), ('yearly_plan', 'Yearly Plan - $120')], max_length=50, null=True),
        ),
    ]
