# Generated by Django 5.2.8 on 2025-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_subscriptionplans_remove_subscribers_plan_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
