# Generated by Django 5.2.8 on 2025-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_alter_subscribers_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='duration_days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
