# Generated by Django 5.2.8 on 2025-12-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_subscriptionplans_duration_days'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('signal', 'Trading Signal'), ('alert', 'Market Alert'), ('news', 'Market News'), ('educational', 'Educational Content'), ('promotional', 'Promotional')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message_body', models.TextField(help_text='Message template. Available variables: {{asset}}, {{type}}, {{entry}}, {{stop_loss}}, {{take_profit}}, {{title}}, {{confidence}}, {{risk}}')),
                ('variables_help', models.TextField(blank=True, help_text='Explanation of available variables')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='trader',
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('signal_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('alert', 'Alert')], max_length=10)),
                ('asset_type', models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('stocks', 'Stocks'), ('indices', 'Indices'), ('commodities', 'Commodities')], max_length=20)),
                ('asset_pair', models.CharField(help_text='e.g., EUR/USD, BTC/USD, AAPL', max_length=50)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('take_profit_1', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('take_profit_2', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('take_profit_3', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('analysis', models.TextField(help_text='Technical analysis and reasoning')),
                ('confidence_level', models.IntegerField(default=50, help_text='Confidence level from 1-100')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('signal_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('whatsapp_template', models.TextField(help_text='Message template for WhatsApp. Use variables: {{asset}}, {{type}}, {{entry}}, {{stop_loss}}, {{take_profit}}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trading Signal',
                'verbose_name_plural': 'Trading Signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkSignalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('send_to_all_active', models.BooleanField(default=False)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('use_template', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_signal_jobs', to=settings.AUTH_USER_MODEL)),
                ('plan_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptionplans')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to='signals.signal')),
            ],
            options={
                'verbose_name': 'Bulk Signal Job',
                'verbose_name_plural': 'Bulk Signal Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='signals.signal')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to='subscriptions.subscribers')),
            ],
            options={
                'verbose_name': 'Signal Recipient',
                'verbose_name_plural': 'Signal Recipients',
                'unique_together': {('signal', 'subscriber')},
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionPlans',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
