# Generated by Django 5.2.8 on 2025-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0006_whatsapptemplate_remove_subscribers_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='take_profit_1',
            new_name='take_profit',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='take_profit_2',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='take_profit_3',
        ),
        migrations.AddField(
            model_name='signal',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Any additional instructions'),
        ),
        migrations.AddField(
            model_name='signal',
            name='asset_name',
            field=models.CharField(default=1, help_text='e.g., Volatility 100 Index', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signal',
            name='confidence',
            field=models.IntegerField(default=75, help_text='Confidence level from 1-100'),
        ),
        migrations.AddField(
            model_name='signal',
            name='entry_type',
            field=models.CharField(choices=[('market', 'Market Execution'), ('limit', 'Limit Order')], default='market', max_length=20),
        ),
        migrations.AddField(
            model_name='signal',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Standard lot size', max_digits=8),
        ),
        migrations.AddField(
            model_name='signal',
            name='market_type',
            field=models.CharField(choices=[('forex', 'Forex'), ('crypto', 'Cryptocurrency'), ('indices', 'Indices'), ('commodities', 'Commodities'), ('stocks', 'Stocks')], default='indices', max_length=20),
        ),
        migrations.AddField(
            model_name='signal',
            name='max_position',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum position size', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='min_position',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum position size', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='risk_note',
            field=models.TextField(default='Ensure proper risk management and only take trades that align with your plan.'),
        ),
        migrations.AddField(
            model_name='signal',
            name='volatility',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='analysis',
            field=models.TextField(blank=True, help_text='Technical analysis and reasoning'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='asset_pair',
            field=models.CharField(help_text='e.g., V100, EUR/USD, BTC/USD', max_length=50),
        ),
        migrations.AlterField(
            model_name='signal',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Market execution if empty', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL'), ('hold', 'HOLD'), ('alert', 'ALERT')], default='buy', max_length=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('sent', 'Sent'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='title',
            field=models.CharField(help_text='e.g., V100 Index Buy Signal', max_length=200),
        ),
        migrations.AlterField(
            model_name='signal',
            name='whatsapp_template',
            field=models.TextField(default='📈 Supreme Traders – {{asset_name}} {{signal_type}} Signal\n\nDirection:  {{signal_type}} – {{asset_name}}\nEntry: {{entry_type}}\n{% if entry_price %}Entry Price:  {{entry_price}}{% endif %}\nStop Loss:  {{stop_loss}}\nTake Profit:  {{take_profit}}\nLot Size:  {{lot_size}}\nNumber of Positions:  Optional — based on your risk appetite\n\nNote: {{risk_note}}\n{% if additional_notes %}{{additional_notes}}{% endif %}'),
        ),
    ]
