# Generated by Django 5.2.8 on 2025-12-09 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('main', 'main'), ('Agent', 'Agent')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
