# Generated by Django 5.2.8 on 2025-12-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberrypi', '0002_ecocashtransfers_transactionotp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocashtransfers',
            name='transaction_type',
            field=models.CharField(choices=[('Agent', 'Agent Transfer'), ('User', 'User Transfer')], default='User', max_length=100),
        ),
    ]
